% Auto-generated by cameraCalibrator app on 19-Mar-2024
%-------------------------------------------------------


% Define images to process
imageFileNames = {'C:\Users\96134\Desktop\ComputerVision\RAW_data6_2D\FD1.JPG',...
    'C:\Users\96134\Desktop\ComputerVision\RAW_data6_2D\FD2.JPG',...
    'C:\Users\96134\Desktop\ComputerVision\RAW_data6_2D\FD3.JPG',...
    'C:\Users\96134\Desktop\ComputerVision\RAW_data6_2D\FD4.JPG',...
    'C:\Users\96134\Desktop\ComputerVision\RAW_data6_2D\FD5.JPG',...
    'C:\Users\96134\Desktop\ComputerVision\RAW_data6_2D\FD6.JPG',...
    };
% Detect calibration pattern in images
detector = vision.calibration.monocular.CheckerboardDetector();
[imagePoints, imagesUsed] = detectPatternPoints(detector, imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Read the first image to obtain image size
originalImage = imread(imageFileNames{1});
[mrows, ncols, ~] = size(originalImage);

% Generate world coordinates for the planar pattern keypoints
squareSize = 20;  % in units of 'millimeters'
worldPoints = generateWorldPoints(detector, 'SquareSize', squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', true, 'EstimateTangentialDistortion', true, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% View reprojection errors
h1=figure; showReprojectionErrors(cameraParams);

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, cameraParams);

% For example, you can use the calibration data to remove effects of lens distortion.
undistortedImage = undistortImage(originalImage, cameraParams);

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('StructureFromMotionExample')
